### ISSUE TITLE
save swc gives dodgy filename in windows build

### ISSUE THREAD

**Issue by AndrewMicallef** [janelia-flyem/NeuTu#13] opened 2016-12-08 03:27 UTC
The save swc function in the windows build saves a file with the extension `.swc)` which is a little annoying as you need to manually rename the file in order to open it again

**Comment by tingzhao** [comment] 2016-12-14 13:38
It appears to be caused by a bug in the Qt library for windows. We're planning to apply some temporary fix.

**Comment by tingzhao** [comment] 2017-01-10 14:38
The bug should be fixed now. Please download the latest version (patched 2017.01.09) from www.neutracing.com.

**Closed** 2017-01-12 18:53 UTC
