### ISSUE TITLE
neutu --command mode should default its configfiles if absent

### ISSUE THREAD

**Issue by pgunn** [janelia-flyem/NeuTu#358] opened 2019-11-26 17:03 UTC
If you install neutu through conda, neutu doesn't have what it needs to use the commandline tools and errors out if you try to use the --command mode.

I have a copy of the sources handy (useful to figure out undocumented things), and it looks like copying ~/src/neutu/neurolabi/json/{trace_config,skeletonize,command_config}.json into ~/neutu_config/json is enough to use the interface.

It'd be great if the conda package of neutu would create default versions of these files when absent if the user tries to use that interface (whether ~/neutu_config/json is the right place to store them is another question)

**Comment by tingzhao** [comment] 2020-01-17 16:09
This was caused by path searching in neutu. The problem should be solved in version 0.3.6. Please have a try.

**Comment by tingzhao** [comment] 2020-01-23 19:43
I'll close the issue for now. You can reopen it if there is still a problem.

**Closed by tingzhao** 2020-01-23 19:43 UTC
